app = "runner"


[env]
  PORT = "10100"

[[services]]
  internal_port = 10100
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "10100"

  # API should work on https://runner.fly.dev/api/v1
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

