# fly.toml app configuration file generated for runner-staging on 2025-07-26T12:42:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'runner-staging'
primary_region = 'lax'

[build]
  dockerfile = 'docker/server-debian/Dockerfile'

[deploy]
  strategy = 'rolling'
  wait_timeout = '5m0s'

[env]
  ENVIRONMENT = 'staging'
  PORT = '10100'

[http_service]
  internal_port = 10100
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/v1/health'

[[services]]
  protocol = 'tcp'
  internal_port = 10100

  [[services.ports]]
    port = 10100
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
