#!/bin/bash

# go to repository root
cd $(git rev-parse --show-cdup)

# check go is installed
if ! which go ; then
echo "go not installed, cannot run precheck"
exit
fi

# format all go files in repository
go fmt ./...

