// Code generated by MockGen. DO NOT EDIT.
// Source: ./engine/runtime/types.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	runtime "github.com/runner-x/runner-x/engine/runtime"
)

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// RunCmd mocks base method.
func (m *MockRuntime) RunCmd(runprops *runtime.RunProps) (*runtime.RunOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunCmd", runprops)
	ret0, _ := ret[0].(*runtime.RunOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunCmd indicates an expected call of RunCmd.
func (mr *MockRuntimeMockRecorder) RunCmd(runprops interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCmd", reflect.TypeOf((*MockRuntime)(nil).RunCmd), runprops)
}
