// Code generated by MockGen. DO NOT EDIT.
// Source: ./engine/runtime/types.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	exec "os/exec"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	runtime "github.com/runner-x/runner-x/engine/runtime"
)

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// IsReady mocks base method.
func (m *MockRuntime) IsReady() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReady")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReady indicates an expected call of IsReady.
func (mr *MockRuntimeMockRecorder) IsReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReady", reflect.TypeOf((*MockRuntime)(nil).IsReady))
}

// RunCmd mocks base method.
func (m *MockRuntime) RunCmd(runprops *runtime.RunProps) (*runtime.RunOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunCmd", runprops)
	ret0, _ := ret[0].(*runtime.RunOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunCmd indicates an expected call of RunCmd.
func (mr *MockRuntimeMockRecorder) RunCmd(runprops interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCmd", reflect.TypeOf((*MockRuntime)(nil).RunCmd), runprops)
}

// SafeRunCmd mocks base method.
func (m *MockRuntime) SafeRunCmd(props *runtime.RunProps) (*runtime.RunOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SafeRunCmd", props)
	ret0, _ := ret[0].(*runtime.RunOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SafeRunCmd indicates an expected call of SafeRunCmd.
func (mr *MockRuntimeMockRecorder) SafeRunCmd(props interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SafeRunCmd", reflect.TypeOf((*MockRuntime)(nil).SafeRunCmd), props)
}

// MockArgProvider is a mock of ArgProvider interface.
type MockArgProvider struct {
	ctrl     *gomock.Controller
	recorder *MockArgProviderMockRecorder
}

// MockArgProviderMockRecorder is the mock recorder for MockArgProvider.
type MockArgProviderMockRecorder struct {
	mock *MockArgProvider
}

// NewMockArgProvider creates a new mock instance.
func NewMockArgProvider(ctrl *gomock.Controller) *MockArgProvider {
	mock := &MockArgProvider{ctrl: ctrl}
	mock.recorder = &MockArgProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArgProvider) EXPECT() *MockArgProviderMockRecorder {
	return m.recorder
}

// Provide mocks base method.
func (m *MockArgProvider) Provide(ctx *context.Context, runprops *runtime.RunProps) *exec.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provide", ctx, runprops)
	ret0, _ := ret[0].(*exec.Cmd)
	return ret0
}

// Provide indicates an expected call of Provide.
func (mr *MockArgProviderMockRecorder) Provide(ctx, runprops interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provide", reflect.TypeOf((*MockArgProvider)(nil).Provide), ctx, runprops)
}

// MockLimiter is a mock of Limiter interface.
type MockLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockLimiterMockRecorder
}

// MockLimiterMockRecorder is the mock recorder for MockLimiter.
type MockLimiterMockRecorder struct {
	mock *MockLimiter
}

// NewMockLimiter creates a new mock instance.
func NewMockLimiter(ctrl *gomock.Controller) *MockLimiter {
	mock := &MockLimiter{ctrl: ctrl}
	mock.recorder = &MockLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimiter) EXPECT() *MockLimiterMockRecorder {
	return m.recorder
}

// ApplyLimits mocks base method.
func (m *MockLimiter) ApplyLimits(rlimits *runtime.ResourceLimits) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyLimits", rlimits)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyLimits indicates an expected call of ApplyLimits.
func (mr *MockLimiterMockRecorder) ApplyLimits(rlimits interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyLimits", reflect.TypeOf((*MockLimiter)(nil).ApplyLimits), rlimits)
}
