// Code generated by MockGen. DO NOT EDIT.
// Source: ./engine/controller/controller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	controller "github.com/runner-x/runner-x/engine/controller"
	runtime "github.com/runner-x/runner-x/engine/runtime"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// SubmitRequest mocks base method.
func (m *MockController) SubmitRequest(runprops *controller.Props) *controller.CtrlRunOutput {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRequest", runprops)
	ret0, _ := ret[0].(*controller.CtrlRunOutput)
	return ret0
}

// SubmitRequest indicates an expected call of SubmitRequest.
func (mr *MockControllerMockRecorder) SubmitRequest(runprops interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRequest", reflect.TypeOf((*MockController)(nil).SubmitRequest), runprops)
}

// runRequest mocks base method.
func (m *MockController) runRequest(runprops *runtime.RunProps, agent *runtime.RuntimeAgent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "runRequest", runprops, agent)
}

// runRequest indicates an expected call of runRequest.
func (mr *MockControllerMockRecorder) runRequest(runprops, agent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "runRequest", reflect.TypeOf((*MockController)(nil).runRequest), runprops, agent)
}
