name: Verify Docker image builds
on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-20.04
    steps:
    -
        name: Checkout repository
        uses: actions/checkout@v2
    -
        name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
    -
        name: Make target mock build
        run: make dkr-build-mock
    -
        name: Make target server build
        run: make dkr-build-server
    -
        name: Make target dev build
        run: make dkr-build-dev
