name: Formatting
on:
  push:
    branches:
      - main
      - dev*
  pull_request:
    branches:
      - main


jobs:

  check-formatting:
    name: Language Lints
    runs-on: ubuntu-latest
    steps:
      - name: Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Gofmt
        run: |
          unformatted_code=$(go fmt ./...)
          [ ! -z "$unformatted_code" ] && exit 1

      - name: Vet
        run: go vet ./...
